name: Docker Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/Dockerfile'
      - 'frontend/Dockerfile'
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/Dockerfile'
      - 'frontend/Dockerfile'
      - 'docker/**'
      - '.github/workflows/docker-build.yml'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: false
        tags: social-media-bot-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: false
        tags: social-media-bot-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  test-docker-compose:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Test Docker Compose configuration
      working-directory: ./docker
      run: |
        # Test docker-compose file syntax
        docker-compose config
        # Test that services can be built (but not started due to dependencies)
        docker-compose build --no-cache